spring:
  application:
    name: springsecurity
  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
#    url: 'jdbc:h2:tcp://localhost/~/test'   # H2 DB 연결 주소 (TCP)
#    url: 'jdbc:h2:~/test'    # H2 DB 연결 주소 (Embedded Mode)
    username: sa        # H2 DB 접속 ID (사용자 지정)
    password:         # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소

  # JPA 설정
  jpa:
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        "[format_sql]": true      # 쿼리 로그 포맷 (정렬)
  sql:
    init:
      mode: always

logging:
  level:
    "[org.hibernate.SQL]": debug  #하이버네이트가 생성하는 SQL 콘솔로깅
    "[org.hibernate.type]": trace #쿼리 파라미터 로그 남기기
      
jwt:
  secretKey: sazya24@gmail.com 

springdoc:
  packages-to-scan: com.example.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    